import "../../../../node_modules/@fortawesome/fontawesome-free/css/all.min.css"
import "../../styles/tailwind-output.css"
import "../../features/backup/tab.js"
import "../../features/restore/tab.js"
import "../../features/custom/tab.js"
import "../../features/cloud/tab.js"
